name: .NET Core Build, Test, & Publish

on: push

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build with dotnet
      run: dotnet build --configuration Release
      working-directory: ./source
    - name: Run unit tests
      run: dotnet test
      working-directory: ./source
    - name: Build NuGet Package
      run: dotnet pack --include-symbols --configuration Release
      working-directory: ./source
    - name: Archive nuget artifacts
      uses: actions/upload-artifact@v1
      with:
        name: nugets
        path: .\nugets
    - name: Create Release
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: |
          .\nugets\*.nupkg
          .\nugets\*.snupkg
    - name: Push NuGet Package
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
      run: dotnet nuget push .\nugets\*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json